## 변경 사항
- 무엇을 변경했나요? (예: 새 컴포넌트 추가, 디자인 수정, 문서 업데이트)  
  - 

## 목적
- 왜 이 변경이 필요한가요? (예: 접근성 개선, 사용자 경험 향상)  
  - 

## 리뷰어에게
- 특별히 확인해 주셨으면 하는 부분이 있나요? (예: 호버 상태, 모바일 뷰포트)  
  - 

---

**기여해주셔서 감사합니다! 🎨**
