# Pull Request Template

## 변경 사항
- 무엇을 변경했나요? (예: 새 컴포넌트 추가, 디자인 수정, 문서 업데이트)  
  - 

## 목적
- 왜 이 변경이 필요한가요? (예: 접근성 개선, 사용자 경험 향상)  
  - 

## 관련 이슈
- 관련 이슈나 티켓이 있다면 링크를 추가해주세요. (형식: `#123` 또는 URL, 없으면 "없음")  
  - 

## 변경된 파일
- 변경한 파일 목록을 나열해주세요.  
  - 
  - 예:
    - `src/components/Button/Button.tsx`
    - `tokens/colors.css`
    - `docs/components.md`

## 웹 접근성
- 접근성 기준(WCAG)을 준수했나요?  
  - [ ] 색상 대비 확인 (4.5:1 이상)  
  - [ ] 키보드 내비게이션 테스트  
  - [ ] 스크린 리더 테스트 (VoiceOver, NVDA 등)  

## 스크린샷
- UI 변경이 있다면 변경 전/후 스크린샷을 첨부해주세요. (드래그 앤 드롭 또는 URL로 추가)  
  - **변경 전**: [이미지링크]
  - **변경 후**: [이미지링크]

## 리뷰어에게
- 특별히 확인해 주셨으면 하는 부분이 있나요? (예: 호버 상태, 모바일 뷰포트)  
  - 

## 체크리스트
- [ ] 코드가 프로젝트 스타일 가이드(Prettier, ESLint)를 준수했나요?  
- [ ] 변경 사항이 기존 컴포넌트나 토큰에 영향을 주지 않나요?

---

**기여해주셔서 감사합니다! 🎨**